= https://isaqb.org[iSAQB] Advanced Level Curriculum API – Application Programming Interfaces

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-api/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-api/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-api.svg["Contributors",link="https://github.com/isaqb-org/curriculum-api/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-api.svg["Issues",link="https://github.com/isaqb-org/curriculum-api/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-api.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the source code of the  iSAQB Advanced Level curriculum *API* in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this template

+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-api.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-api.git --recursive
----
--

== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle: `./gradle-tools/gradlew buildDocs`
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
    languages = ["DE", "EN"]

----


== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by the curator group of the module API.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.

[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
