=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: API Lifecycle verstehen

Teilnehmer:innen kennen verschiedene Schritte des Entwicklungszyklus eines API Produkts und die typischen Aufgaben, die bei diesen Schritten anfallen.
Die Aufteilung in Planung und Anforderungsanalyse, Design und Prototyping, Entwicklung, Testing und Qualitätsprüfung, Deployment und Veröffentlichung, Betrieb und Wartung sowie Verbesserung und Iteration sind bekannt.
Ebenfalls bekannt sind die verschiedenen Lebensphasen eines APIs wie Prototyp, produktiver Betrieb, Deprecation und das Abschalten.

[[LZ-6-2]]
==== LZ 6-2: APIs als Produkte verwalten

APIs kommen oft in lose gekoppelten Szenarien zum Einsatz und aus diesem Grund ist es sinnvoll, sie als Produkte zu managen.
Teilnehmer:innen verstehen, was es bedeutet, ein API als Produkt zu verwalten.
Dies beginnt beim Zielgruppenfokus, berücksichtigt Fragen der Nutzbarkeit, von Feedback sowie Verbesserung und behandelt auch Fragen von Deprecation und der Bereitstellung von Alternativen.

[[LZ-6-3]]
==== LZ 6-3: API Lifecycle Tooling kennen

Teilnehmer:innen kennen typische Tools für den Einsatz im API Lifecycle zur Unterstützung von Produzenten und Konsumenten wie Linting, Testing (z. B. Contract Testing), Mocking sowie Betrieb (API Gateways).
Teilnehmer:innen können mit einigen dieser Tools praktisch arbeiten und verstehen, sie in das Gesamtbild des API Lifecycle Tooling einzuordnen.

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Understand the API lifecycle

Participants understand the various stages of the development cycle of an API product and the typical tasks that are performed throughout these stages.
Participants understand the various stages of planning, requirements analysis, design, prototyping, development, testing, quality assurance, deployment, publication, operations, and maintenance, and how to improve an API product in an iterative way.
Participants also know the different lifecycle stages of an API such as prototype, production, deprecation, and sunsetting.

[[LG-6-2]]
==== LG 6-2: Manage APIs as products

APIs are often used in loosely coupled scenarios and for this reason it makes sense to manage them as products.
Participants understand what it means to manage an API as a product.
API product management starts with focus on a set of consumers, deals with questions of usability, includes feedback, and also handles questions of deprecation and how to provide alternatives.

[[LG-6-3]]
==== LG 6-3: Know API lifecycle tooling

Participants know typical tools that are used throughout the API lifecycle. These tools support producers as well as consumers and include functionality such as linting, testing (e.g., contract testing), mocking, and operations (API gateways).
Participants gain practical knowledge of some of these tools and understand how they fit into the bigger picture of API lifecycle tooling.

// end::EN[]
