=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Das Konzept der "API Economy" verstehen

Das Konzept der "API Economy" wird in seiner gesamten Breite verstanden und Teilnehmer:innen können beurteilen, wie ihre Produkte und Aktivitäten dort eingeordnet werden können.

[[LZ-2-2]]
==== LZ 2-2: Verschiedene Arten der API Wertschöpfung kennen

Teilnehmer:innen kennen und verstehen die verschiedenen Arten, wie APIs zur Wertschöpfung beitragen können. Die verschiedenen Arten können auf der obersten Ebene unterschieden werden:

- Private APIs die innerhalb einer Organisationen eingesetzt werden
- Partner APIs die mit etablierten Partnern genutzt werden
- Public APIs die als Produkte nach aussen angeboten werden

Teilnehmer:innen verstehen die verschiedenen Optionen innerhalb und Zusammenhänge zwischen diesen Kategorien und den Wert einer übergreifenden API Strategie.

[[LZ-2-3]]
==== LZ 2-3: API Business Models verstehen

Teilnehmer:innen haben ein detailliertes Verständnis der möglichen Geschäftsmodelle von APIs und einiger ausgewählter Beispiele. Ausgehend von den verschiedenen Arten der API Wertschöpfung können Teilnehmer:innen bestehende Geschäftsmodelle analysieren und mit APIs gezielt ergänzen und erweitern.

[[LZ-2-4]]
==== LZ 2-4: APIs und Digitale Transformation verstehen

Teilnehmer:innen können APIs einordnen in das grössere Bild digitaler Transformation. APIs werden als notwendiger (aber nicht hinreichender) Teil einer digitalen Transformation verstanden, und andere notwendige Aspekte sind ebenfalls bekannt.

// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: Understanding the "API Economy"

[[LG-2-2]]
==== LG 2-2: Knowing Various Ways of API Value Creation

[[LG-2-3]]
==== LG 2-3: Understanding API Business Models

[[LG-2-4]]
==== LG 2-4: Understanding APIs and Digital Transformation

// end::EN[]
