=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Grundlegende API-Stile verstehen

Die folgenden API-Stile werden verstanden und ihre Vor- sowie Nachteile können gegeneinander abgewogen werden:

* RPC (Remote Procedure Call)
* Resourcen-basiert
* Hypermedia
* Query
* Events & asynchrone Kommunikation

[[LZ-3-2]]
==== LZ 3-2: Populäre API-Technologien ein- und den jeweiligen API-Stilen zuordnen

Teilnehmer:innen können die wichtigsten populären API-Technologien einordnen und kennen den von ihnen implementierten API-Stil, z.B.:

* gRPC
* HTTP APIs
* REST
* GraphQL

[[LZ-3-3]]
==== LZ 3-3: Auswahlkriterien und Konsequenzen von API-Stilen & Technologien kennen

Teilnehmer:innen erwerben ein Verständnis für Kriterien, wann welche Stile/Technologien besser oder weniger gut passen und welche Konsequenzen die jeweilige Auswahl mit sich bringt.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Understanding Fundamental API Styles

The following API styles are understood by participants and their advantages and drawbacks can be compared:

* RPC (Remote Procedure Call)
* Resource-based
* Hypermedia
* Query
* Events & asynchronous communications

[[LG-3-2]]
==== LG 3-2: Understanding Popular API Technologies and Associating Them With API Styles

Participants are able to classify the most important API technologies and know which API style they are implementing, for example:

* gRPC
* HTTP APIs
* REST
* GraphQL

[[LG-3-3]]
==== LG 3-3: Understanding When to Use Which Style and Technology and the Consequences of That Choice

Participants gain knowledge of criteria when certain styles and technologies are a good or not-so-good fit, and which consequences the selection will have.

// end::EN[]
