=== {learning-goals}

// tag::DE[]
[[LZ-7-1]]
==== LZ 7-1: Grundlagen von Kommunikationssicherheit kennen

Teilnehmer:innen kennen die Grundlagen von Kommunikationssicherheit und können Technologien wie TCP, HTTP und TLS einordnen.
Sie haben ein Bewusstsein für die Notwendigkeit sicherer Kommunikation - auch bei unternehmensinternen Schnittstellen.

[[LZ-7-2]]
==== LZ 7-2: Relevante Technologien im API-Umfeld verstehen

Teilnehmer:innen verstehen, wie HTTPS, HTTP-Authentisierung, OAuth und OpenID Connect funktionieren, inwiefern diese sich unterscheiden und wie die Technologien bei der Absicherung von APIs helfen.

[[LZ-7-3]]
==== LZ 7-3: OWASP API Security Top 10 kennen

Teilnehmer:innen kennen die OWASP API Security Top 10 und verstehen die darin beschriebenen häufigsten Sicherheitsprobleme von APIs.


// end::DE[]

// tag::EN[]
[[LG-7-1]]
==== LG 7-1: Understand Communications Security Fundamentals

Participants understand the foundations of communications security and are able to relate them to technologies such as TCP, HTTP, and TLS.
Participants understand the relevance of secure communications, even in the case of internal interfaces.

[[LG-7-2]]
==== LG 7-2: Understand Security Technologies for APIs

Participants understand HTTPS, HTTP authentication, OAuth, and OpenID Connect, how they relate and differ, and how these technologies help when it comes to securing APIs.

[[LG-7-3]]
==== LG 7-3: Understand OWASP API Security Top 10

Participants know the OWASP API Security Top 10 and understand the most common security issues of APIs.

// end::EN[]
