=== {learning-goals}

// tag::DE[]
[[LZ-7-1]]
==== LZ 7-1: Grundlagen von Kommunikationssicherheit kennen

Teilnehmer:innen kennen die Grundlagen von Kommunikationssicherheit und können Technologien wie TCP, HTTP und TLS einordnen.
Sie haben ein Bewusstsein für die Notwendigkeit sicherer Kommunikation - auch bei unternehmensinternen Schnittstellen.

[[LZ-7-2]]
==== LZ 7-2: Relevante Technologien im API-Umfeld verstehen

Teilnehmer:innen verstehen, wie HTTPS, HTTP-Authentisierung, OAuth und OpenID Connect funktionieren, inwiefern diese sich unterscheiden und wie die Technologien bei der Absicherung von APIs helfen.

// end::DE[]

// tag::EN[]
[[LG-7-2]]
==== LG 7-2: Understanding Communications Security Fundamentals

Participants understand the foundations of communications security and are able to relate them to technologies such as TCP, HTTP, and TLS.
Participants understand the relevance of secure communications, even in the case of internal interfaces.

[[LG-7-2]]
==== LG 7-2: Understanding Security Technologies for APIs

Participants understand how HTTPS, HTTP authentication, OAuth, and OpenID Connect, how they relate and differ, and how these technologies heklp when it comes to securing APIs.

// end::EN[]
