=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: APIs in die Historie der Softwareentwicklung einordnen

Teilnehmer:innen können APIs in die Geschichte der Programmierung, Computernetzwerke, verteilten Systeme und Softwarearchitektur einordnen.
Die Entwicklung von lokalen APIs zu netzwerkbasierten APIs und die aktuelle API Landschaft werden in ihrem Gesamtkontext verstanden.

[[LZ-1-2]]
==== LZ 1-2: Unterschiedliche Integrationsstile und -konzepte vergleichen

Unterschiedliche Ansätze zur Systemintegration sind den Teilnehmer:innen bekannt und können gegeneinander abgegrenzt werden, insbesondere:

* Integration über eine Datenbank
* Dateibasierte Systemintegration
* Integration durch synchrone Kommunikation, z. B. RPC (Remote Procedure Call)
* Integration durch asynchrone Kommunikation, z. B. Message Queues

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understand APIs in the context of software development

Participants understand APIs in the context of programming, computer networks, distributed systems, and software architecture.
They understand the development from local APIs to network-based APIs and the current API landscape in the overall context.

[[LG-1-2]]
==== LG 1-2: Compare different styles and concepts of integration

Different approaches for systems integration are known to participants and can be compared and contrasted, specifically:

* Integration through a shared database
* File-based systems integration
* Integration through synchronous communications, for example RPC (Remote Procedure Call)
* Integration through asynchronous communications, for example message queues

// end::EN[]
