=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Bedeutung von API-Design verstehen

Teilnehmer:innen verstehen, weshalb ein gewissenhaftes Design von APIs von großer Bedeutung ist und welchen Einfluss dies auf die Nutzbarkeit, Wartung, Weiterentwicklung und Verbreitung hat. Teilnehmer:innen verstehen, dass sich Anbieter:innen und Konsument:innen ohne zentrale Kontrolle weiterentwickeln können, und welche Herausforderungen daraus resultieren.

[[LZ-4-2]]
==== LZ 4-2: API-Design als "Outside-in"-Ansatz anwenden

Zu den wichtigsten Zielen von APIs zählt die effiziente Anbindung von Konsument:innen an die Schnittstelle des Betreibers.
Das Design sollte auf die Anforderungen der Konsument:innen fokussiert sein und nicht entlang eventuell bestehender Systeme, Use Cases oder Datenbanken.
Teilnehmer:innen kennen und verstehen die Ansätze von API-First und konsumentengetriebenem API-Design.

[[LZ-4-3]]
==== LZ 4-3: Offenheit und Erweiterbarkeit als wichtige Aspekte für die Weiterentwicklung von APIs interpretieren

Teilnehmer:innen kennen lose Kopplung, Postel's Law, die Bedeutung von Vorwärts- und Rückwärtskompatibilität und welchen Einfluss diese auf die Möglichkeit der Weiterentwicklung von APIs haben.
Darüber hinaus erfahren Teilnehmer:innen, welche Konsequenzen dies für die Implementierung von APIs und deren Clients in streng und statisch typisierten Programmiersprachen hat.

[[LZ-4-4]]
==== LZ 4-4: Versionierung von APIs verstehen

Teilnehmer:innen erlangen ein Verständnis für verschiedene Aspekte der Versionierung und wie sie innerhalb des Lebenszyklus eines API-Produkts verwendet werden. Folgende Konzepte sind bekannt:

* Kompatibilität und die Unterscheidung zwischen Vorwärts- und Rückwärtskompatibilität
* Versionierungsidentifikation und Semantic Versioning als spezifisches Modell
* Verschiedene Arten der Versionierungsidentifikation für APIs (z.B. Domain-Namen, URI-Pfade, HTTP-Header, Information im Payload)

[[LZ-4-5]]
==== LZ 4-5: Good Practices für gelungenes API-Design kennen

Teilnehmer:innen lernen bewährte und verbreitete Ansätze für das Design von HTTP-APIs kennen und verstehen die Vorteile und Herausforderungen.
Hierzu zählen u.a.:

* URL-Pfade
* korrekte Verwendung von HTTP-Methoden oder -Operationen für häufig benötigte Funktionalität wie Suchen, Filtern oder Sortieren
* Caching zur Performance-Verbesserung von APIs
* Formatvorschläge wie JSON:API oder HAL
* Problem Details for HTTP APIs (RFC 9457)
* API-Design-Styleguides


// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Understand the significance of API design

Participants understand why careful API design is important and which influence it has on usability, maintenance, evolution, and adoption. Participants understand that providers and consumers may evolve without centralized control and what the resulting challenges are.

[[LG-4-2]]
==== LG 4-2: Use the "outside-in" approach for API design

One of the most important goals of APIs is to efficiently connect consumers with the provider's interface.
API design should be focused on the needs of the consumers.
It shouldn't be based on existing systems, existing use cases, or databases.
Participants know and understand the approaches of API First and consumer-oriented API design.

[[LG-4-3]]
==== LG 4-3: Understand openness and extensibility as important aspects for API evolution

Participants understand loose coupling, Postel's law, the concepts of forward and backward compatibility, and the importance of these concepts for the evolution of APIs.
Participants also understand the consequences for API implementation in strong and statically typed languages.

[[LG-4-4]]
==== LG 4-4: Understand API versioning

Participants gain knowledge of various aspects of versioning and how these are applied during the lifecycle of an API product. The following concepts are known:

* Compatibility and the difference between forward and backward compatibility
* Version identification in general and semantic versioning as a specific model for version identification
* Different ways of version identification for APIs (for example, domain name, URI path, HTTP header, payload-based)

[[LG-4-5]]
==== LG 4-5: Know good practices for API design

Participants learn about established and widely used aspects for API design and understand their advantages and challenges.
These aspects include:

* URL paths
* Using correct HTTP methods or operations for frequently needed functionality such as searching, filtering, or sorting
* Caching as a way to improve API performance
* Proposed formats such as JSON:API or HAL
* Problem Details for HTTP APIs (RFC 9457)
* API Design Style Guides

// end::EN[]
